# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\club_join.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_text = QtWidgets.QLineEdit(self.centralwidget)
        self.name_text.setGeometry(QtCore.QRect(290, 180, 311, 51))
        self.name_text.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.name_text.setObjectName("name_text")
        self.age_text = QtWidgets.QLineEdit(self.centralwidget)
        self.age_text.setGeometry(QtCore.QRect(290, 250, 311, 51))
        self.age_text.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.age_text.setObjectName("age_text")
        self.bloodtype_town = QtWidgets.QLineEdit(self.centralwidget)
        self.bloodtype_town.setGeometry(QtCore.QRect(290, 390, 311, 51))
        self.bloodtype_town.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.bloodtype_town.setObjectName("bloodtype_town")
        self.hometown_text = QtWidgets.QLineEdit(self.centralwidget)
        self.hometown_text.setGeometry(QtCore.QRect(290, 320, 311, 51))
        self.hometown_text.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.hometown_text.setObjectName("hometown_text")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(160, 180, 91, 41))
        self.name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name.setStyleSheet("font: 75 23pt \"Agency FB\";")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.age = QtWidgets.QLabel(self.centralwidget)
        self.age.setGeometry(QtCore.QRect(160, 240, 91, 51))
        self.age.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.age.setStyleSheet("font: 75 23pt \"Agency FB\";")
        self.age.setAlignment(QtCore.Qt.AlignCenter)
        self.age.setObjectName("age")
        self.howetown = QtWidgets.QLabel(self.centralwidget)
        self.howetown.setGeometry(QtCore.QRect(120, 320, 171, 41))
        self.howetown.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.howetown.setStyleSheet("font: 75 23pt \"Agency FB\";")
        self.howetown.setAlignment(QtCore.Qt.AlignCenter)
        self.howetown.setObjectName("howetown")
        self.bloodtype = QtWidgets.QLabel(self.centralwidget)
        self.bloodtype.setGeometry(QtCore.QRect(130, 390, 161, 41))
        self.bloodtype.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bloodtype.setStyleSheet("font: 75 23pt \"Agency FB\";")
        self.bloodtype.setAlignment(QtCore.Qt.AlignCenter)
        self.bloodtype.setObjectName("bloodtype")
        self.name_5 = QtWidgets.QLabel(self.centralwidget)
        self.name_5.setGeometry(QtCore.QRect(130, 0, 511, 111))
        self.name_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name_5.setStyleSheet("font: 75 35pt \"Agency FB\";\n"
"color: white;")
        self.name_5.setAlignment(QtCore.Qt.AlignCenter)
        self.name_5.setObjectName("name_5")
        self.motto_text = QtWidgets.QLineEdit(self.centralwidget)
        self.motto_text.setGeometry(QtCore.QRect(290, 460, 311, 51))
        self.motto_text.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.motto_text.setText("")
        self.motto_text.setObjectName("motto_text")
        self.motto = QtWidgets.QLabel(self.centralwidget)
        self.motto.setGeometry(QtCore.QRect(120, 460, 161, 41))
        self.motto.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.motto.setStyleSheet("font: 75 23pt \"Agency FB\";")
        self.motto.setAlignment(QtCore.Qt.AlignCenter)
        self.motto.setObjectName("motto")
        self.save_bt = QtWidgets.QPushButton(self.centralwidget)
        self.save_bt.setGeometry(QtCore.QRect(670, 510, 93, 28))
        self.save_bt.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Agency FB\";\n"
"color : white;")
        self.save_bt.setObjectName("save_bt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name.setText(_translate("MainWindow", "name"))
        self.age.setText(_translate("MainWindow", "age"))
        self.howetown.setText(_translate("MainWindow", "Hometown"))
        self.bloodtype.setText(_translate("MainWindow", "blood_type"))
        self.name_5.setText(_translate("MainWindow", "동아리 회원가입"))
        self.motto.setText(_translate("MainWindow", "motto"))
        self.save_bt.setText(_translate("MainWindow", "SAVE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
