# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cds.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(270, 30, 291, 101))
        self.title.setStyleSheet("font: 75 48pt \"Agency FB\";")
        self.title.setObjectName("title")
        self.graphics = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphics.setGeometry(QtCore.QRect(90, 150, 611, 301))
        self.graphics.setObjectName("graphics")
        self.cds_value = QtWidgets.QLabel(self.centralwidget)
        self.cds_value.setGeometry(QtCore.QRect(210, 470, 171, 71))
        self.cds_value.setStyleSheet("font: 22pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius : 10px; ")
        self.cds_value.setText("")
        self.cds_value.setObjectName("cds_value")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 480, 101, 51))
        self.label_2.setStyleSheet("font: 75 26pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "CDS graph"))
        self.label_2.setText(_translate("MainWindow", "CDS : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
