# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\coin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(340, 40, 121, 61))
        self.title.setStyleSheet("font: 75 36pt \"Agency FB\";")
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setObjectName("title")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(40, 130, 211, 171))
        self.background.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius : 10px;")
        self.background.setText("")
        self.background.setObjectName("background")
        self.input_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.input_edit.setGeometry(QtCore.QRect(520, 130, 261, 41))
        self.input_edit.setObjectName("input_edit")
        self.Search = QtWidgets.QPushButton(self.centralwidget)
        self.Search.setGeometry(QtCore.QRect(520, 180, 261, 41))
        self.Search.setObjectName("Search")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 150, 111, 31))
        self.label.setStyleSheet("font: 87 11pt \"Arial Black\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.now_state = QtWidgets.QLabel(self.centralwidget)
        self.now_state.setGeometry(QtCore.QRect(60, 190, 171, 41))
        self.now_state.setStyleSheet("font: 9pt \"Agency FB\";\n"
"color: rgb(255, 0, 0);")
        self.now_state.setAlignment(QtCore.Qt.AlignCenter)
        self.now_state.setObjectName("now_state")
        self.fluctuation_state = QtWidgets.QLabel(self.centralwidget)
        self.fluctuation_state.setGeometry(QtCore.QRect(60, 240, 171, 41))
        self.fluctuation_state.setStyleSheet("font: 9pt \"Agency FB\";\n"
"color: rgb(255, 0, 0);")
        self.fluctuation_state.setAlignment(QtCore.Qt.AlignCenter)
        self.fluctuation_state.setObjectName("fluctuation_state")
        self.background_2 = QtWidgets.QLabel(self.centralwidget)
        self.background_2.setGeometry(QtCore.QRect(40, 330, 211, 171))
        self.background_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius : 10px;")
        self.background_2.setText("")
        self.background_2.setObjectName("background_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 350, 111, 31))
        self.label_2.setStyleSheet("font: 87 11pt \"Arial Black\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.now_state_2 = QtWidgets.QLabel(self.centralwidget)
        self.now_state_2.setGeometry(QtCore.QRect(60, 390, 171, 41))
        self.now_state_2.setStyleSheet("font: 9pt \"Agency FB\";\n"
"color: rgb(255, 0, 0);")
        self.now_state_2.setAlignment(QtCore.Qt.AlignCenter)
        self.now_state_2.setObjectName("now_state_2")
        self.fluctuation_state_2 = QtWidgets.QLabel(self.centralwidget)
        self.fluctuation_state_2.setGeometry(QtCore.QRect(60, 440, 171, 41))
        self.fluctuation_state_2.setStyleSheet("font: 9pt \"Agency FB\";\n"
"color: rgb(255, 0, 0);")
        self.fluctuation_state_2.setAlignment(QtCore.Qt.AlignCenter)
        self.fluctuation_state_2.setObjectName("fluctuation_state_2")
        self.background_3 = QtWidgets.QLabel(self.centralwidget)
        self.background_3.setGeometry(QtCore.QRect(270, 130, 211, 171))
        self.background_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius : 10px;")
        self.background_3.setText("")
        self.background_3.setObjectName("background_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 150, 111, 31))
        self.label_3.setStyleSheet("font: 87 11pt \"Arial Black\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.now_state_3 = QtWidgets.QLabel(self.centralwidget)
        self.now_state_3.setGeometry(QtCore.QRect(290, 190, 171, 41))
        self.now_state_3.setStyleSheet("font: 9pt \"Agency FB\";\n"
"color: rgb(255, 0, 0);")
        self.now_state_3.setAlignment(QtCore.Qt.AlignCenter)
        self.now_state_3.setObjectName("now_state_3")
        self.fluctuation_state_3 = QtWidgets.QLabel(self.centralwidget)
        self.fluctuation_state_3.setGeometry(QtCore.QRect(290, 240, 171, 41))
        self.fluctuation_state_3.setStyleSheet("font: 9pt \"Agency FB\";\n"
"color: rgb(255, 0, 0);")
        self.fluctuation_state_3.setAlignment(QtCore.Qt.AlignCenter)
        self.fluctuation_state_3.setObjectName("fluctuation_state_3")
        self.background_4 = QtWidgets.QLabel(self.centralwidget)
        self.background_4.setGeometry(QtCore.QRect(270, 330, 211, 171))
        self.background_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius : 10px;")
        self.background_4.setText("")
        self.background_4.setObjectName("background_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 350, 111, 31))
        self.label_4.setStyleSheet("font: 87 11pt \"Arial Black\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.now_state_4 = QtWidgets.QLabel(self.centralwidget)
        self.now_state_4.setGeometry(QtCore.QRect(290, 390, 171, 41))
        self.now_state_4.setStyleSheet("font: 9pt \"Agency FB\";\n"
"color: rgb(255, 0, 0);")
        self.now_state_4.setAlignment(QtCore.Qt.AlignCenter)
        self.now_state_4.setObjectName("now_state_4")
        self.fluctuation_state_4 = QtWidgets.QLabel(self.centralwidget)
        self.fluctuation_state_4.setGeometry(QtCore.QRect(290, 440, 171, 41))
        self.fluctuation_state_4.setStyleSheet("font: 9pt \"Agency FB\";\n"
"color: rgb(255, 0, 0);")
        self.fluctuation_state_4.setAlignment(QtCore.Qt.AlignCenter)
        self.fluctuation_state_4.setObjectName("fluctuation_state_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Coin"))
        self.Search.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.now_state.setText(_translate("MainWindow", "TextLabel"))
        self.fluctuation_state.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.now_state_2.setText(_translate("MainWindow", "TextLabel"))
        self.fluctuation_state_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.now_state_3.setText(_translate("MainWindow", "TextLabel"))
        self.fluctuation_state_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.now_state_4.setText(_translate("MainWindow", "TextLabel"))
        self.fluctuation_state_4.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
